apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - roommate-user-clusterrole.yaml
  - csidriver.yaml
  - daemonset.yaml
images:
  - name: ghcr.io/middlendian/roommate-csi
    newTag: dev
